### ISSUE TITLE
Large Library UI issue with 5 per line and backgrounds

### ISSUE THREAD

**Issue by staticnation** [suchmememanyskill/SDH-CssLoader#32] opened 2022-10-08 08:11 UTC
Video of the issue:
https://www.youtube.com/watch?v=lgNAGu7zkKM

Thread where plugins were identified as the cause:
https://www.reddit.com/r/DeckSupport/comments/xyg86x/comment/irh7zam/

**Comment by suchmememanyskill** [comment] 2022-10-08 08:29
1. This is the cssloader repository, not a theme repository. Next time, make an issue on the actual theme.
2. Duplicate of https://github.com/suchmememanyskill/Steam-Deck-Themes/issues/5

**Closed** 2022-10-08 08:29 UTC

**Comment by staticnation** [comment] 2022-10-08 08:57
Thanks for pointing out the correct place to report (It has been a hassle
to find where the issue needed to be reported, just look at the same issue
on the decky loader page), I dont expect this to  be fixed, I just want
wanted to report it so its a known issue. Have a great day.
