### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by qlmmm** [suchmememanyskill/SDH-CssLoader#59] opened 2023-01-31 05:37 UTC
Hello, when I was using it, I clicked install, but there was no response, and the theme could not be downloaded

**Comment by suchmememanyskill** [comment] 2023-01-31 09:41
Hi, please tell me the exact steps to reproduce. What did you press in exact order to get here? What theme exactly is broken? Is it one of them, or all of them?

Also, please reproduce the issue, then capture the logs of cssloader. You can do so by running `journalctl -u plugin_loader -b0 | grep CSS > log.txt` in konsole on the desktop. A log.txt file will be generated at the current working directory, likely your home folder if you opened konsole from the start menu.

**Comment by qlmmm** [comment] 2023-01-31 14:47
> 

All themes cannot be downloaded。The error is“result failed！process exited with error code 2”

**Comment by qlmmm** [comment] 2023-01-31 14:48
> 你好，請告訴我重現的具體步驟。您按確切的順序按什麼到達這裡？到底什麼主題壞了？是其中之一，還是全部？
> 
> 另外，請重現問題，然後捕獲 cssloader 的日誌。您可以通過`journalctl -u plugin_loader -b0 | grep CSS > log.txt`在桌面上的 konsole 中運行來執行此操作。將在當前工作目錄中生成一個 log.txt 文件，如果您從開始菜單打開 konsole，則可能是您的主文件夾。

https://github.com/suchmememanyskill/SDH-CssLoader/issues/59#issuecomment-1410047947

> Hi, please tell me the exact steps to reproduce. What did you press in exact order to get here? What theme exactly is broken? Is it one of them, or all of them?
> 
> Also, please reproduce the issue, then capture the logs of cssloader. You can do so by running `journalctl -u plugin_loader -b0 | grep CSS > log.txt` in konsole on the desktop. A log.txt file will be generated at the current working directory, likely your home folder if you opened konsole from the start menu.

All themes cannot be downloaded。The error is“result failed！process exited with error code 2”

**Comment by suchmememanyskill** [comment] 2023-01-31 14:57
Can tou via both an external pc and a webbrowser on the deck visit [the site](https://deckthemes.com) and try to download a theme?

Also, can i have the full logs please

**Comment by qlmmm** [comment] 2023-01-31 15:07
> Can tou via both an external pc and a webbrowser on the deck visit [the site](https://deckthemes.com) and try to download a theme?
> 
> Also, can i have the full logs please

Jan 31 22:58:41 steamdeck PluginLoader[1600]: [loader][INFO]: Loaded CSS Loader
Jan 31 22:58:42 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] Initializing css loader...
Jan 31 22:58:42 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] Max supported manifest version: 5
Jan 31 22:58:42 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] Result failed! [Errno 17] File exists: '/home/deck/homebrew/themes' -> '/home/deck/.local/share/Steam/steamui/themes_custom'
Jan 31 22:58:42 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] Mappings:
Jan 31 22:58:42 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] QuickAccess -> ['QuickAccess', 'QuickAccess_.*']
Jan 31 22:58:42 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] MainMenu -> ['MainMenu', 'MainMenu_.*']
Jan 31 22:58:42 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] All -> ['SP', 'QuickAccess', 'QuickAccess_.*', 'MainMenu', 'MainMenu_.*', 'Steam Big Picture Mode']
Jan 31 22:58:42 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] SP -> ['SP', 'Steam Big Picture Mode']
Jan 31 22:58:42 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] Loading themes...
Jan 31 23:00:12 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] Downloading https://api.deckthemes.com/blobs/5b24b53c-eba6-4a21-a159-684258b7bd6c to /tmp/tmphiq8jrtk...
Jan 31 23:00:14 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] Unzipping /tmp/tmphiq8jrtk/theme.zip
Jan 31 23:00:14 steamdeck PluginLoader[1706]: [css_utils][INFO]: [CSS_Loader] Result failed! Process exited with error code 2

**Comment by suchmememanyskill** [comment] 2023-01-31 15:15
It seems like it's failing at unzipping the file. Exit code 2 seems to indicate an issue with the downloaded file. Can you try downloading the same theme via a normal webbrowser?

Also, you seem to also be running into issue #57

**Comment by suchmememanyskill** [comment] 2023-01-31 15:27
Due to issue 57, you cannot currently load any themes (Temporary fix is to switch to steamos stable). But, besides that, you can manually install a theme by unzipping the theme you downloaded in ~/homebrew/themes.

I don't know currently why the download is failing, though. 'Unzipping failed' can mean litearlly anything, but from what i can see the api is returning the correct result

**Comment by qlmmm** [comment] 2023-01-31 16:10
> Due to issue 57, you cannot currently load any themes (Temporary fix is to switch to steamos stable). But, besides that, you can manually install a theme by unzipping the theme you downloaded in ~/homebrew/themes.
> 
> I don't know currently why the download is failing, though. 'Unzipping failed' can mean litearlly anything, but from what i can see the api is returning the correct result

Thank you for your answer, I found out that the reason for these problems is that I don't have permission under the deck folder, sorry to bother you

**Comment by beebls** [comment] 2023-02-02 01:13
Ah the age old "broken installer" issue, glad you could figure it out!

Gonna close this, but if it breaks again, feel free to comment here and I can re-open the issue

**Closed by beebls** 2023-02-02 01:13 UTC
